// Mock database - In production, this would be replaced with a real database
import type { HeroSlide, Department, FeaturedProduct, CategoryShowcase } from "@/types/admin"

// Hero Slides Data
export const heroSlides: HeroSlide[] = [
  {
    id: "1",
    title: "VISITA NUESTRO",
    subtitle: "CATÁLOGO DIGITAL",
    cta: "HAZ CLIC AQUÍ",
    image: "/images/hero-tablet.png",
    background: "bg-gradient-to-r from-blue-900 via-blue-800 to-purple-900",
    order: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "PRODUCTOS DE",
    subtitle: "CALIDAD GARANTIZADA",
    cta: "CONOCE MÁS",
    image: "/placeholder.svg?height=400&width=600",
    background: "bg-gradient-to-r from-gray-900 via-gray-800 to-blue-900",
    order: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "SERVICIO",
    subtitle: "PROFESIONAL",
    cta: "CONTÁCTANOS",
    image: "/placeholder.svg?height=400&width=600",
    background: "bg-gradient-to-r from-green-900 via-blue-800 to-purple-900",
    order: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Departments Data
export const departments: Department[] = [
  {
    id: "1",
    name: "Gases Industriales",
    icon: "Settings",
    color: "bg-blue-800",
    href: "/productos?categoria=Gases Industriales",
    order: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Equipos de Soldadura",
    icon: "Zap",
    color: "bg-blue-800",
    href: "/productos?categoria=Equipos de Soldadura",
    order: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Herramientas",
    icon: "Wrench",
    color: "bg-blue-800",
    href: "/productos?categoria=Herramientas",
    order: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // {
  //   id: "4",
  //   name: "Autopartes",
  //   icon: "Car",
  //   color: "bg-blue-800",
  //   href: "/productos?categoria=Autopartes",
  //   order: 4,
  //   isActive: true,
  //   createdAt: new Date().toISOString(),
  //   updatedAt: new Date().toISOString(),
  // },
  {
    id: "5",
    name: "Equipos Neumáticos",
    icon: "Fuel",
    color: "bg-blue-800",
    href: "/productos?categoria=Equipos Neumáticos",
    order: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Seguridad Industrial",
    icon: "Cog",
    color: "bg-blue-800",
    href: "/productos?categoria=Seguridad Industrial",
    order: 6,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Featured Products Data
export const featuredProducts: FeaturedProduct[] = [
  {
    id: "1",
    name: "Tanque de Oxígeno",
    category: "Gases",
    price: 1250.0,
    image: "/placeholder.svg?height=200&width=200",
    href: "/productos/tanque-oxigeno",
    order: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Soldadora MIG",
    category: "Soldadura",
    price: 8500.0,
    image: "/placeholder.svg?height=200&width=200",
    href: "/productos/soldadora-mig",
    order: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Kit de Herramientas",
    category: "Herramientas",
    price: 2100.0,
    originalPrice: 2400.0,
    image: "/placeholder.svg?height=200&width=200",
    href: "/productos/kit-herramientas",
    order: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Filtro de Aceite",
    category: "Autopartes",
    price: 180.0,
    image: "/placeholder.svg?height=200&width=200",
    href: "/productos/filtro-aceite",
    order: 4,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Category Showcase Data
export const categoryShowcase: CategoryShowcase[] = [
  {
    id: "1",
    name: "Gases Industriales",
    description: "Oxígeno, argón, acetileno y más gases para uso industrial",
    productCount: "500+ productos",
    image: "/placeholder.svg?height=200&width=300",
    href: "/productos?categoria=Gases Industriales",
    order: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Equipos de Soldadura",
    description: "Soldadoras, electrodos y accesorios profesionales",
    productCount: "300+ productos",
    image: "/placeholder.svg?height=200&width=300",
    href: "/productos?categoria=Equipos de Soldadura",
    order: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Herramientas",
    description: "Herramientas manuales y eléctricas de calidad",
    productCount: "800+ productos",
    image: "/placeholder.svg?height=200&width=300",
    href: "/productos?categoria=Herramientas",
    order: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Helper functions for CRUD operations
export const generateId = () => Date.now().toString()

export const updateTimestamp = (item: any) => ({
  ...item,
  updatedAt: new Date().toISOString(),
})
